const sharedTreatments = {
  es: [
    ["Microimplante Capilar", "Microimplante capilar FUE", "Técnica FUE", "Redistribución de unidades foliculares mediante una técnica mínimamente invasiva y personalizada.", "La técnica FUE permite extraer unidades foliculares de una zona donante e implantarlas de forma individual en las áreas que requieren mayor cobertura.", ["Diseño adaptado a cada paciente", "Procedimiento planificado por el equipo profesional", "Controles y seguimiento durante la evolución"]],
    ["Plasma Rico en Plaquetas", "Plasma rico en plaquetas", "PRP capilar", "Tratamiento complementario orientado al fortalecimiento y cuidado del cabello.", "El PRP capilar utiliza una concentración de plaquetas obtenida de la propia sangre del paciente como parte de un plan orientado al cuidado del cuero cabelludo.", ["Aplicación localizada", "Puede complementar otros tratamientos", "La indicación depende de una evaluación previa"]],
    ["Mesoterapia Capilar", "Mesoterapia capilar", "Tratamiento personalizado", "Aplicación localizada según las necesidades identificadas durante la evaluación.", "Consiste en aplicaciones localizadas seleccionadas según las características del cuero cabelludo y los objetivos definidos durante la consulta.", ["Plan individualizado", "Sesiones definidas según cada caso", "Seguimiento de la respuesta al tratamiento"]],
    ["Microdermopigmentación Capilar", "Microdermopigmentación capilar", "Efecto visual de densidad", "Técnica orientada a recrear visualmente una mayor densidad capilar de manera personalizada.", "Mediante la aplicación precisa de pigmentos se busca recrear visualmente folículos y aportar una apariencia de mayor densidad en áreas seleccionadas.", ["Diseño previo personalizado", "Pigmentación adaptada al tono del paciente", "Indicaciones de cuidado y controles posteriores"]],
  ],
  en: [
    ["Hair Transplant", "FUE hair transplant", "FUE technique", "Redistribution of follicular units through a personalized, minimally invasive technique.", "The FUE technique extracts follicular units from a donor area and implants them individually in areas requiring greater coverage.", ["A design tailored to each patient", "Procedure planned by the professional team", "Checkups and follow-up throughout the process"]],
    ["Platelet-Rich Plasma", "Platelet-rich plasma", "Hair PRP", "A complementary treatment designed to strengthen and care for the hair.", "Hair PRP uses a concentration of platelets obtained from the patient’s own blood as part of a scalp-care plan.", ["Targeted application", "May complement other treatments", "Indication depends on a prior assessment"]],
    ["Hair Mesotherapy", "Hair mesotherapy", "Personalized treatment", "Targeted application based on the needs identified during the assessment.", "It consists of targeted applications selected according to the characteristics of the scalp and the goals defined during the consultation.", ["Individualized plan", "Sessions defined for each case", "Monitoring of the response to treatment"]],
    ["Scalp Micropigmentation", "Scalp micropigmentation", "Visual density effect", "A personalized technique designed to create the visual appearance of greater hair density.", "Through the precise application of pigments, the aim is to visually recreate follicles and provide the appearance of greater density in selected areas.", ["Personalized preliminary design", "Pigmentation adapted to the patient’s tone", "Aftercare guidance and follow-up"]],
  ],
  pt: [
    ["Microimplante Capilar", "Microimplante capilar FUE", "Técnica FUE", "Redistribuição de unidades foliculares por meio de uma técnica minimamente invasiva e personalizada.", "A técnica FUE permite extrair unidades foliculares de uma área doadora e implantá-las individualmente nas regiões que precisam de maior cobertura.", ["Desenho adaptado a cada paciente", "Procedimento planejado pela equipe profissional", "Controles e acompanhamento durante a evolução"]],
    ["Plasma Rico em Plaquetas", "Plasma rico em plaquetas", "PRP capilar", "Tratamento complementar voltado ao fortalecimento e cuidado dos cabelos.", "O PRP capilar utiliza uma concentração de plaquetas obtida do próprio sangue do paciente como parte de um plano de cuidado do couro cabeludo.", ["Aplicação localizada", "Pode complementar outros tratamentos", "A indicação depende de uma avaliação prévia"]],
    ["Mesoterapia Capilar", "Mesoterapia capilar", "Tratamento personalizado", "Aplicação localizada de acordo com as necessidades identificadas durante a avaliação.", "Consiste em aplicações localizadas selecionadas conforme as características do couro cabeludo e os objetivos definidos na consulta.", ["Plano individualizado", "Sessões definidas para cada caso", "Acompanhamento da resposta ao tratamento"]],
    ["Microdermopigmentação Capilar", "Microdermopigmentação capilar", "Efeito visual de densidade", "Técnica personalizada para recriar visualmente uma maior densidade capilar.", "Por meio da aplicação precisa de pigmentos, busca-se recriar visualmente os folículos e proporcionar uma aparência de maior densidade nas áreas selecionadas.", ["Desenho prévio personalizado", "Pigmentação adaptada ao tom do paciente", "Orientações de cuidados e controles posteriores"]],
  ],
};

export const locales = ["es", "en", "pt"];

export const copy = {
  es: {
    locale: "es-AR", path: "/", consult: "Consultar", nav: ["Tratamientos", "Resultados", "Profesional", "Preguntas"],
    menu: ["Cerrar menú", "Abrir menú"], hero: ["Microimplante capilar · Técnica FUE", "Sembramos el comienzo de una nueva etapa", "Cada gran cambio comienza con un primer paso, y nos alegra acompañarte en este proceso. Gracias por permitirnos ser parte de este camino. Desde este momento estaremos a tu lado en cada etapa, con un tratamiento personalizado, atención profesional y el compromiso de brindarte el cuidado que este momento merece.", "Solicitar evaluación", "Conocé los resultados"],
    treatments: ["Tratamientos", "Soluciones para cada necesidad capilar", "La evaluación inicial permite definir un plan acorde a cada caso y acompañar su evolución.", "Conocer más", "Solicitar una evaluación", "Cerrar información del tratamiento"],
    process: ["Cómo trabajamos", "Un proceso claro y acompañado", "Cada etapa está pensada para brindar información, tranquilidad y seguimiento."],
    processSteps: [["Evaluación", "Conocemos tu caso, objetivos y antecedentes."], ["Plan personalizado", "Definimos la alternativa más adecuada para vos."], ["Tratamiento", "Realizamos el procedimiento con precisión y cuidado."], ["Seguimiento", "Realizamos un seguimiento personalizado de tu evolución durante todo el proceso, con controles en cada etapa, hasta que juntos logremos el resultado esperado."]],
    results: ["Casos reales", "Evoluciones que cuentan una historia", "Cada proceso es único. Te mostramos registros reales del seguimiento realizado por el equipo de Tomento.", "Comparación", "Seguimiento capilar", "Consultar mi caso", "Antes", "Después", "Comparaciones disponibles", "Las imágenes corresponden a seguimientos reales. Los tiempos de evolución y los resultados pueden variar según cada paciente."],
    professionals: ["Profesionales", "Un equipo que acompaña cada etapa"],
    faq: ["Información útil", "Preguntas frecuentes", "Respuestas generales para conocer los tratamientos y el proceso de atención en Tomento.", "La información es orientativa y no reemplaza una evaluación profesional."],
    contact: ["Contacto", "Solicitá tu evaluación", "Completá el formulario y enviá tu consulta directamente por WhatsApp.", "Canal directo", "Tu consulta llega por WhatsApp", "Al enviar el formulario se abrirá WhatsApp con tus datos y tu mensaje preparados para enviarlos directamente a Tomento.", "Redes", "Seguinos en Instagram", "Resultados, novedades y contenido de Tomento Capilar.", "Ver Instagram", "Ubicación", "Abrir mapa"],
    footer: ["Microimplante y tratamientos capilares personalizados en CABA.", "Explorar", "Profesionales", "Contacto", "La información del sitio es orientativa y no reemplaza una evaluación profesional.", "Volver arriba"],
  },
  en: {
    locale: "en", path: "/en/", consult: "Contact us", nav: ["Treatments", "Results", "Team", "Questions"],
    menu: ["Close menu", "Open menu"], hero: ["Hair transplant · FUE technique", "Planting the beginning of a new chapter", "Every major change begins with a first step, and we are glad to be with you throughout this process. From this moment on, we will support you at every stage with personalized treatment, professional care, and the commitment this moment deserves.", "Request an assessment", "View results"],
    treatments: ["Treatments", "Solutions for every hair-care need", "The initial assessment allows us to define a plan for each case and follow its progress.", "Learn more", "Request an assessment", "Close treatment information"],
    process: ["How we work", "A clear and supported process", "Each stage is designed to provide information, reassurance, and follow-up."],
    processSteps: [["Assessment", "We learn about your case, goals, and medical history."], ["Personalized plan", "We define the most appropriate option for you."], ["Treatment", "We perform the procedure with precision and care."], ["Follow-up", "We provide personalized follow-up throughout your progress, with checkups at every stage until we reach the expected outcome together."]],
    results: ["Real cases", "Progress that tells a story", "Every process is unique. Explore real follow-up records from the Tomento team.", "Comparison", "Hair follow-up", "Ask about my case", "Before", "After", "Available comparisons", "Images show real follow-up cases. Progress times and results may vary from patient to patient."],
    professionals: ["Professionals", "A team supporting every stage"],
    faq: ["Useful information", "Frequently asked questions", "General answers about Tomento treatments and patient care.", "This information is for guidance only and does not replace a professional assessment."],
    contact: ["Contact", "Request your assessment", "Complete the form and send your inquiry directly through WhatsApp.", "Direct channel", "Your inquiry goes to WhatsApp", "When you submit the form, WhatsApp will open with your details and message ready to send directly to Tomento.", "Social media", "Follow us on Instagram", "Results, updates, and content from Tomento Capilar.", "View Instagram", "Location", "Open map"],
    footer: ["Personalized hair transplants and treatments in Buenos Aires.", "Explore", "Professionals", "Contact", "This website provides general information and does not replace a professional assessment.", "Back to top"],
  },
  pt: {
    locale: "pt-BR", path: "/pt/", consult: "Consultar", nav: ["Tratamentos", "Resultados", "Profissionais", "Dúvidas"],
    menu: ["Fechar menu", "Abrir menu"], hero: ["Microimplante capilar · Técnica FUE", "Plantamos o começo de uma nova etapa", "Toda grande mudança começa com um primeiro passo, e ficamos felizes em acompanhar você nesse processo. A partir de agora, estaremos ao seu lado em cada etapa, com tratamento personalizado, atendimento profissional e o compromisso de oferecer o cuidado que este momento merece.", "Solicitar avaliação", "Ver resultados"],
    treatments: ["Tratamentos", "Soluções para cada necessidade capilar", "A avaliação inicial permite definir um plano adequado para cada caso e acompanhar sua evolução.", "Saiba mais", "Solicitar uma avaliação", "Fechar informações do tratamento"],
    process: ["Como trabalhamos", "Um processo claro e acompanhado", "Cada etapa foi pensada para oferecer informação, tranquilidade e acompanhamento."],
    processSteps: [["Avaliação", "Conhecemos seu caso, objetivos e antecedentes."], ["Plano personalizado", "Definimos a alternativa mais adequada para você."], ["Tratamento", "Realizamos o procedimento com precisão e cuidado."], ["Acompanhamento", "Acompanhamos sua evolução de forma personalizada durante todo o processo, com controles em cada etapa, até alcançarmos juntos o resultado esperado."]],
    results: ["Casos reais", "Evoluções que contam uma história", "Cada processo é único. Veja registros reais do acompanhamento realizado pela equipe Tomento.", "Comparação", "Acompanhamento capilar", "Consultar meu caso", "Antes", "Depois", "Comparações disponíveis", "As imagens correspondem a acompanhamentos reais. O tempo de evolução e os resultados podem variar para cada paciente."],
    professionals: ["Profissionais", "Uma equipe que acompanha cada etapa"],
    faq: ["Informações úteis", "Perguntas frequentes", "Respostas gerais para conhecer os tratamentos e o atendimento da Tomento.", "As informações são orientativas e não substituem uma avaliação profissional."],
    contact: ["Contato", "Solicite sua avaliação", "Preencha o formulário e envie sua consulta diretamente pelo WhatsApp.", "Canal direto", "Sua consulta chega pelo WhatsApp", "Ao enviar o formulário, o WhatsApp será aberto com seus dados e sua mensagem prontos para envio direto à Tomento.", "Redes sociais", "Siga-nos no Instagram", "Resultados, novidades e conteúdos da Tomento Capilar.", "Ver Instagram", "Localização", "Abrir mapa"],
    footer: ["Microimplante e tratamentos capilares personalizados em Buenos Aires.", "Explorar", "Profissionais", "Contato", "As informações deste site são orientativas e não substituem uma avaliação profissional.", "Voltar ao topo"],
  },
};

export function getCopy(locale = "es") {
  return { ...copy[locale], treatmentItems: sharedTreatments[locale] };
}
